import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Gift,
  Share2,
  Anchor,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LogOut,
  LucideProps,
  Moon,
  Menu,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  Film,
  User,
  Star,
  Pencil,
  Bookmark,
  Video,
  MessageSquare,
  LayoutDashboard,
  Link,
  X,
  type Icon as LucideIcon,
  Github,
  Youtube,
  Instagram,
  Linkedin,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Anchor,
  menu: Menu,
  logout: LogOut,
  link: Link,
  comment: MessageSquare,
  dashboard: LayoutDashboard,
  star: Star,
  share: Share2,
  bookmark: Bookmark,
  like: Gift,
  video: Film,
  write: Pencil,
  live: Video,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  youtube: Youtube,
  instagram: Instagram,
  linkedin: Linkedin
};
